routes/change.py
import datetime

from flask import Blueprint,  render_template, request,  redirect, g, abort, url_for
from auth import login_session_required
from logger import logger
from models import  db, ChangeManagement

change_bp = Blueprint('change', __name__)

@change_bp.route('/', methods=['GET'])
@login_session_required
def change_list():
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)

    changes  = ChangeManagement.query.all()


    return render_template('change_list.html', changes=changes)


@change_bp.route('/create', methods=['GET', 'POST'])
@login_session_required
def create_change():
    if 'VIEW_CHANGE' not in g.permissions:
        return abort(403)

    if request.method == 'POST':
        title = request.form['name']
        description = request.form['description']
        status = request.form['status']
        priority = request.form['priority']
        impact = request.form['impact']
        change_type = request.form['change_type']
        requested_by_id = request.form['requested_by_id']
        proposed_time = request.form['proposed_time']
        executed_time = request.form['executed_time']
        software_id = request.form['software_id']
        hardware_id = request.form['hardware_id']


        # DB transaction
        try:
            with db.session.begin(nested=True):
                change = ChangeManagement(
                    title = title,
                    description = description,
                    status = status,
                    priority = priority,
                    impact = impact,
                    change_type =  change_type,
                    requested_by_id = requested_by_id,
                    proposed_time =  proposed_time,
                    executed_time = executed_time,
                    software_id = software_id,
                    hardware_id = hardware_id,
                    created_at = datetime.datetime.now(datetime.timezone.utc),
                    updated_at =datetime.datetime.now(datetime.timezone.utc)
                )
                db.session.add(change)

                db.session.commit()
                return redirect(url_for('change.change_list'))
        except Exception as e:
            db.session.rollback()
            logger.error(e)






    return render_template('create_change.html')

@change_bp.route('/<int:change_id>/edit', methods=['GET', 'POST'])
@login_session_required
def edit_change(change_id):
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)
    change = ChangeManagement.query.get_or_404(change_id)

    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description'],
        status = request.form['status'],
        priority = request.form['priority'],
        impact = request.form['impact'],
        change_type = request.form['change_type'],
        requested_by_id = request.form['requested_by_id'],
        proposed_time = request.form['proposed_time'],
        executed_time = request.form['executed_time'],
        software_id = request.form['software_id'],
        hardware_id = request.form['hardware_id']


        # DB transaction
        try:
            with db.session.begin(nested=True):# Due to two transactions so need the nested  to allow the second.
                #update change
                change.title = title
                change.description = description
                change.status = status,
                change.priority = priority,
                change.impact = impact,
                change.change_type = change_type,
                change.requested_by_id = requested_by_id,
                change.proposed_time = proposed_time,
                change.executed_time = executed_time,
                change.software_id = software_id,
                change.hardware_id = hardware_id,
                change.updated_at = datetime.datetime.now(datetime.timezone.utc),

                db.session.commit() # gets user.id

                return redirect(url_for('change.change_list'))

        except Exception as e:
            db.session.rollback()
            print('Could not find the change ' + str(change_id))
            print(e)
# if  using get it wil drop to this section
    return render_template('create_change.html',change=change)

@change_bp.route('/<int:change_id>/delete', methods=['POST'])
@login_session_required
def delete_change(change_id):
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)

    #Update change
    ChangeManagement.query.filter_by(id= change_id).delete()
    db.session.commit()# commit the change


    return redirect(url_for('change.change_list'))

routes/hardware.py
import datetime

from flask import Blueprint,  render_template, g, abort
from auth import login_session_required

from models import db,  Hardware

hardware_bp = Blueprint('hardware', __name__)

@hardware_bp.route('/', methods=['GET'])
@login_session_required
def hardware_list():
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)

    hardwares  = Hardware.query.all()






    return render_template('hardware_list.html', hardwares=hardwares)

routes/home.py
from flask import Blueprint,  render_template
from sqlalchemy import func

from auth import login_session_required
from models import User, db, Vulnerability, Software, IncidentManagement

home_bp = Blueprint('home', __name__)

@home_bp.route('/', methods=['GET' ])
@login_session_required
def home():
    security_summary = (
        db.session.query(
            Vulnerability.severity,
            func.count(Vulnerability.cve_id)
        )
        .join(
            Software,
            (Software.name == Vulnerability.product) &
            (Software.vendor == Vulnerability.vendor) &
            (
                (Software.version == Vulnerability.version)  |
                (Vulnerability.version == '*') |
                (Vulnerability.version == '-')
            )
        )
        .group_by(Vulnerability.severity)
        .all()
    )

    incident_summary = (
        db.session.query(
            IncidentManagement.priority,
            func.count(IncidentManagement.id)
        )

        .group_by(IncidentManagement.priority)
        .all()
    )

    return render_template('home.html', security_summary=dict(security_summary), incident_summary=dict(incident_summary)) #Change the data structure

routes/security.py
from flask import Blueprint, render_template, abort, g, request
from auth import login_session_required
from models import db, Software, Hardware, Vulnerability, IncidentManagement

security_bp = Blueprint('security', __name__)

@security_bp.route('/', methods=['GET'])
@login_session_required
def vulnerability_list():
    if 'VIEW_SECURITY' not in g.permissions:
        return abort(403)
# Joining the Software- Hardware and Vulnerabilty table
    search = request.args.get('search')
    severity = request.args.get('severity')
    base_query = (
        db.session.query(Software, Hardware, Vulnerability, IncidentManagement) # The tables to be joined
        .join(
            Vulnerability, # vulnerability
            (Software.name == Vulnerability.product) & # software name - vul prod
            (Software.vendor == Vulnerability.vendor) &# software vendor - vul vendor
            (
                    (Software.version == Vulnerability.version) | # serching on version
                    (Vulnerability.version == '*') | # searching on *
                    (Vulnerability.version == '-') # searching on -
            )
        )
        .join(
            Hardware,  # hardware
            Hardware.id == Software.hardware_id #  joining the forign key
        )
        .outerjoin( # All incidents to be displayed
            IncidentManagement,
            IncidentManagement.cve_id == Vulnerability.cve_id
        )
    )
    if search:
        base_query = base_query.filter(Vulnerability.product.ilike(f'%{search}%')) # ilike ignore the case the % is a wild card before and after.  This search can be incresed to use OR  if more  fields are needed
    if severity:
        base_query = base_query.filter(Vulnerability.severity == severity) # search by severity
    results = (
        base_query
        .order_by(
            db.case(
                    (Vulnerability.severity == 'CRITICAL', 1),
                    (Vulnerability.severity == 'HIGH', 2),
                    (Vulnerability.severity == 'MEDIUM', 3),
                    (Vulnerability.severity == 'LOW', 4),
                    else_ = 5
            )
        )
        .all()
    )
    return render_template('security.html', results=results)

routes/software.py
import datetime

from flask import Blueprint,  render_template, request,  redirect, g, abort, url_for
from auth import login_session_required
from logger import logger
from models import db, Hardware, Software

software_bp = Blueprint('software', __name__)

@software_bp.route('/', methods=['GET'])
@login_session_required
def software_list():

    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)

    softwares  = Software.query \
        .join(Hardware, Hardware.id == Software.hardware_id) \
        .all()
    print(softwares[0])




    return render_template('software_list.html', softwares=softwares)

routes/user.py
import datetime
import bcrypt#(Bodnar, 2024)
import re#(Python, 2009)
from flask import Blueprint,  render_template, request,  redirect, g, abort, url_for
from auth import login_session_required
from logger import logger
from models import User, UserRole, Role, db

user_bp = Blueprint('user', __name__)

def hash_password(plain_password):
    # The below is generating hashed password using salt, which is encoded with using utf-8.
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(plain_password.encode('utf-8'), salt)
    return hashed.decode('utf-8')

def is_valid_password(plain_password):

    # Must be at least 8 characters
    if len(plain_password) < 8:
        return False
     # Must be at least 1  uppercase
    if not re.search(r'[A-Z]', plain_password):
        return False
    # Must be at least 1 lowercase
    if not re.search(r'[a-z]', plain_password):
        return False
    # Must be at least 1 numer
    if not re.search(r'[0-9]', plain_password):
        return False
    # Must be at least speacial ?=.*!@#$%^&(),:{}|<> character"
    if not re.search(r'[?=.*!@#$%^&(),:{}|<>]', plain_password):
        return False

    return True

@user_bp.route('/', methods=['GET'])
@login_session_required
def user_list():
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)

    users  = User.query.all()


    return render_template('user_list.html', users=users)


@user_bp.route('/create', methods=['GET', 'POST'])
@login_session_required
def create_user():
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)
    roles = Role.query.all()
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        password = request.form['password']
        role_ids = request.form.getlist('roles')
        if not is_valid_password(password):
            return render_template('create_user.html', roles=roles, error="Must be at least 8 characters and include uppercase, lowercase, number, and special character")
        if not role_ids:
            return render_template('create_user.html', roles=roles, error="Select at least one role")
        # DB transaction
        try:
            with db.session.begin(nested=True):
                user = User(
                    username = username,
                    email_text = email,
                    first_name = first_name,
                    last_name = last_name,
                    password = hash_password(password),
                    created_at = datetime.datetime.now(datetime.timezone.utc),
                    updated_at =datetime.datetime.now(datetime.timezone.utc),
                )
                db.session.add(user)
                db.session.flush()
                for role_id in role_ids:
                    user_role = UserRole(user_id = user.id, role_id=int(role_id))
                    db.session.add(user_role)
                db.session.commit()
                return redirect(url_for('user.user_list'))
        except Exception as e:
            db.session.rollback()
            logger.error(e)
    return render_template('create_user.html', roles=roles)

@user_bp.route('/<int:user_id>/edit', methods=['GET', 'POST'])
@login_session_required
def edit_user(user_id):
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)
    user = User.query.get_or_404(user_id)
    roles = Role.query.all()
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        password = request.form['password']
        role_ids = request.form.getlist('roles')

        if not is_valid_password(password):
            return render_template('create_user.html', user=user, roles=roles, error="Must be at least 8 characters and include uppercase, lowercase, number, and special character")

        if not role_ids:
            return render_template('create_user.html', user=user, roles=roles, error="Select at least one role")

        # DB transaction
        try:
            with db.session.begin(nested=True):# Due to two transactions so need the nested  to allow the second.
                #update user
                user.username = username
                user.email = email
                user.first_name = first_name
                user.last_name = last_name
                user.password = hash_password(password),
                user.updated_at = datetime.datetime.now(datetime.timezone.utc)

                #update user role
                UserRole.query.filter_by(user_id=user_id).delete()# we are deletig the user role from the database and then will update again with the new set

                for role_id in role_ids:
                    user_role = UserRole(user_id = user.id, role_id=int(role_id))
                    db.session.add(user_role)

                db.session.commit()

                return redirect(url_for('user.user_list'))

        except Exception as e:
            db.session.rollback()
            logger.error('Could not find the user ' + str(user_id))
            logger.error(e)
# if  using get it wil drop to this section
    return render_template('create_user.html',user=user, roles=roles)

@user_bp.route('/<int:user_id>/delete', methods=['POST'])
@login_session_required
def delete_user(user_id):
    if 'VIEW_ADMIN' not in g.permissions:
        return abort(403)

    #Update user role
    UserRole.query.filter_by(user_id= user_id).delete()
    User.query.filter_by(id=user_id).delete()
    db.session.commit()# commit the change


    return redirect(url_for('user.user_list'))

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF=8">
    <title>Dashboard</title>

   <!--css style sheet import from bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">


    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

    {% block body %}{% endblock %}

    <!--jave script import from bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>

    <!--chart.js import from CDNJS-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"  crossorigin="anonymous"></script>
    <script>
    {% block script %}{% endblock %}
    </script>

</body>
</html>

templates/change_list.html
{% extends 'layout.html' %}

{% block main %}
<h1>Change!</h1>
{% if 'VIEW_ADMIN' in g.permissions %}
        <a class="btn btn-primary my-3" href="{{url_for('change.create_change') }}" role="button">Create Change</a>
{% endif %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Status</th>
        <th scope="col">Priority</th>
        <th scope="col">Impact</th>
        <th scope="col">Change Type</th>
        <th scope="col">requested By ID</th>
        <th scope="col">proposed Time</th>
        <th scope="col">executed Time</th>
        <th scope="col">software ID</th>
        <th scope="col">hardware ID</th>
        <th scope="col">Updated</th>

    </tr>
    </thead>
    <tbody>
    {% for change in changes %}

    <tr>
        <th scope="row">{{change.id}}</th>
        <td>{{change.title}}</td>
        <td>{{change.description}}</td>
        <td>{{change.status}}</td>
        <td>{{change.priority}}</td>
        <td>{{change.impact}}</td>
        <td>{{change.change_type}}</td>
        <td>{{change.requested_by_id}}</td>
        <td>{{change.proposed_time}}</td>
        <td>{{change.executed_time}}</td>
        <td>{{change.software_id}}</td>
        <td>{{change.hardware_id}}</td>
        <td>{{change.updated_at}}</td>
        <td>{{change.created_at}}</td>



        <td>
            <a href="{{ url_for('change.edit_change', change_id=change.id) }}" type="button" class="btn btn-secondary btn-sm">Edit</a>


            <form method="post" action="{{ url_for('change.delete_change', change_id=change.id)}}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete')">
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>

        </td>
    </tr>
    {% else %}
    <tr>

        <td colspan="13" class=text-center> No Changes Found</td>

    </tr>
    {% endfor %}


    </tbody>
</table>

{% endblock %}

templates/create_problem.html
{% extends 'layout.html' %}
{% block main %}
<h1 class="mb-4">
    {% if problem %}
        Edit problem
    {%else %}
        Create New problem
    {% endif %}
</h1>
{%if error %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>

{% endif %}
<form method="post">
    <label for="title">title:</label><br>
    <input type="text" id="title" name="title" required value="{{problem.title if problem else ''}}"><br>
    <label for="description">Description</label><br>
    <input id="description" name="description" required value="{{problem.description if problem else ''}}"><br>
    <label for="status">Status</label><br>
    <input id="status" name="status" required value="{{problem.status if problem else ''}}"><br>
    <label for="priority">Priority</label><br>
    <input id="priority" name="priority" required value="{{problem.priority if problem else ''}}"><br>
    <label for="impact">Impact</label><br>
    <input id="impact" name="impact" required value="{{problem.impact if problem else ''}}"><br>
    <label for="assignee_id">Assignee ID</label><br>
    <input id="assignee_id" name="assignee_id" required value="{{problem.assignee_id if problem else ''}}"><br>
    <label for="created_id">Created ID</label><br>
    <input id="created_id" name="created_id" required value="{{problem.created_id if problem else ''}}"><br>
    <label for="root_cause">Root Cause</label><br>
    <input id="root_cause" name="root_cause" required value="{{problem.root_cause if problem else ''}}"><br>
    <label for="resolution">Resolution</label><br>
    <input id="resolution" name="resolution" required value="{{problem.root_cause if problem else ''}}"><br>
    <label for="incident_id">Incident ID</label><br>
    <input id="incident_id" name="incident_id" required value="{{problem.incident_id if problem else ''}}"><br>
        <label class="form-label">incident_id</label><br>
    {% for incident in incidents %}
    <div class="from-check form-check-inline">
        <input
                class="form-check-input"
                type="checkbox"
                name="incident_id"
                value="{{incident.id}}"
                id="incident{{incident.id}}"
                {% if problem and incident.id in problem.incident_id%} checked {%endif%}
        />
        <label class="form-check-labl" for="incident{{incident.id}}">{{incident.name}}</label>
    </div>
    <br>
    {% endfor %}


    <button type="submit" class="btn btn-success">
        {% if problem %}
            Update problem
        {% else %}
            Create problem
        {% endif %}
    </button>
    <a  href="{{url_for('problem.problem_list') }}" class="btn btn-secondary" role="button">Cancel</a>




</form>

{% endblock %}

templates/hardware_list.html
{% extends 'layout.html' %}

{% block main %}
<h1>HARDWARE!</h1>

<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Type</th>
        <th scope="col">Manufacturer</th>
        <th scope="col">Model</th>
        <th scope="col">Location</th>
        <th scope="col">Status</th>
        <th scope="col">Purchase Date</th>
        <th scope="col">Up Dated</th>
        <th scope="col">Created Date</th>

    </tr>
    </thead>
    <tbody>
    {% for hardware in hardwares %}

    <tr>
        <th scope="row">{{hardware.id}}</th>
        <td>{{hardware.name}}</td>
        <td>{{hardware.type}}</td>
        <td>{{hardware.manufacturer}}</td>
        <td>{{hardware.model}}</td>
        <td>{{hardware.location}}</td>
        <td>{{hardware.status}}</td>
        <td>{{hardware.purchase_date}}</td>
        <td>{{hardware.updated_at}}</td>
        <td>{{hardware.created_at}}</td>

    </tr>
    {% else %}
    <tr>

        <td colspan="13" class=text-center> No hardware Found</td>

    </tr>
    {% endfor %}


    </tbody>
</table>

{% endblock %}

templates/layout.html
{% extends 'base.html' %}

{% block body %}


<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="/">DASHBOARD</a>

    <ul class="navbar-nav flex-row d-md-none">
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false"
                    aria-label="Toggle search">
            </button>
        </li>
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                    aria-label="Toggle navigation">
            </button>
        </li>
    </ul>
    <div id="navbarSearch" class="navbar-search w-100 collapse">
        <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
    </div>
</header>

<div class="container-fluid">
    <div class="row">
        <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
            <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
                 aria-labelledby="sidebarMenuLabel">
                <div class="offcanvas-header"><h5 class="offcanvas-title" id="sidebarMenuLabel">DASHBOARD SIDE BAR</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                            data-bs-target="#sidebarMenu" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
                    <ul class="nav flex-column">

                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2"  href="{{url_for('home.home') }}">
                            Home
                        </a>
                        </li>

                        {% if 'VIEW_ADMIN' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2"  href="{{url_for('user.user_list') }}">
                            ADMIN:User
                        </a>
                        </li>
                        {% endif %}
                        {% if 'VIEW_ADMIN' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2"  href="{{url_for('role.role_list') }}">
                            ADMIN:Role
                        </a>
                        </li>
                        {% endif %}
                        {% if 'VIEW_PROBLEMS' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2"  href="{{url_for('problem.problem_list') }}">
                            Problem
                        </a>
                        </li>
                        {% endif %}
                        {% if 'VIEW_INCIDENTS' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2"  href="{{url_for('incident.incident_list') }}">
                            Incident
                        </a>
                        </li>
                        {% endif %}
                        {% if 'VIEW_CHANGE' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2"  href="{{url_for('change.change_list') }}">
                            Change
                        </a>
                        </li>
                        {% endif %}
                        {% if 'VIEW_SECURITY' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2" href="{{url_for('security.vulnerability_list') }}">
                            SECURITY
                        </a>
                        </li>
                        {% endif %}
                        {% if 'VIEW_ADMIN' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2" href="{{url_for('hardware.hardware_list') }}">
                            Hardware
                        </a>
                        </li>
                        {% endif %}
                          {% if 'VIEW_ADMIN' in g.permissions %}
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2" href="{{url_for('software.software_list') }}">
                            Software
                        </a>
                        </li>
                        {% endif %}

                    </ul>
                    <hr class="my-3">
                    <ul class="nav flex-column mb-auto">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2" href="#">
                                Settings
                            </a>
                        </li>
                        <li class="nav-item"><a class="nav-link d-flex align-items-center gap-2" href="{{url_for('authentication.logout')}}">
                            Sign out
                        </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            {%block main %} {% endblock%}

        </main>
    </div>
</div>


{% endblock %}

templates/security.html
{% extends 'layout.html' %}

{% block main %}
<h1 class="my-5">Security</h1>
<form method="get" class="row my-4">
<div class="col-md-4">
    <input type="text" name="search" class="form-control" placeholder="Search for products.." value="{{request.args.get('search', '')}}">
</div>
<div class="col-md-4">
    <select class="form-select" name="severity">
      <option selected disabled> Filter severity</option>
        <option value="CRITICAL" {% if request.args.get('severity') == 'CRITICAL' %} selected {% endif %}>CRITICAL</option>
        <option value="HIGH" {% if request.args.get('severity') == 'HIGH' %} selected {% endif %}>HIGH</option>
        <option value="MEDIUM" {% if request.args.get('severity') == 'MEDIUM' %} selected {% endif %}>MEDIUM</option>
        <option value="LOW" {% if request.args.get('severity') == 'LOW' %} selected {% endif %}>LOW</option>
    </select>
</div>

<div class="col-md-4">
    <button type="submit" class="btn btn-secondary">Search</button>
    <a href="{{url_for('security.vulnerability_list')}}" type="button" class="btn btn-outline-secondary">Clear</a>

</div>
</form>

<table class="table">
    <thead>
    <tr>
        <th scope="col">CVE ID</th>
        <th scope="col">Severity</th>
        <th scope="col">CVSS Score</th>
        <th scope="col">Vendor</th>
        <th scope="col">Product</th>
        <th scope="col">Version</th>
        <th scope="col">Description</th>
        <th scope="col">Hardware Name</th>
        <th scope="col">Hardware Location</th>
        <th scope="col">Action</th>




    </tr>
    </thead>
    <tbody>
    {% for software, hardware, vulnerability, incident in results %}

    <tr class="{{vulnerability.severity | severity_class}}">
        <th scope="row">{{vulnerability.cve_id}}</th>
        <td>{{vulnerability.severity}}</td>
        <td>{{vulnerability.cvss_score}}</td>
        <td>{{vulnerability.vendor}}</td>
        <td>{{vulnerability.product}}</td>
        <td>{{software.version}}</td>
        <td>{{vulnerability.description}}</td>
        <td>{{hardware.name}}</td>
        <td>{{hardware.location}}</td>



        <td>
            {% if incident %}
             <a href="{{url_for('incident.edit_incident', incident_id=incident.id) }}" type="button" class="btn btn-outline-secondary btn-sm">EDIT Incident</a>
            {% else %}
            <a href="{{url_for('incident.create_incident') }}?cve_id={{vulnerability.cve_id}}&prefill_software_id={{software.id}}" type="button" class="btn btn-secondary btn-sm">Create Incident</a>
            {% endif %}


        </td>
    </tr>
    {% else %}
    <tr>

        <td colspan="10" class=text-center> System Secure </td>

    </tr>
    {% endfor %}


    </tbody>
</table>



{% endblock %}

templates/user_list.html
{% extends 'layout.html' %}
{% block main %}
<h1> ADMIN Home!</h1>
<a class="btn btn-primary my-3" href="{{url_for('user.create_user') }}" role="button">Create User</a>
<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">FirstName</th>
        <th scope="col">LastName</th>
      <th scope="col">Role</th>
        <th scope="col">Actions</th>

    </tr>
    </thead>
    <tbody>
    {% for user in users %}
    <tr>
        <th scope="row">{{user.id}}</th>
        <td>{{user.username}}</td>
        <td>{{user.email_text}}</td>
        <td>{{user.first_name}}</td>
        <td>{{user.last_name}}</td>
      <td>{{user.roles | map(attribute='name') | join(', ') }}</td>
        <td>
            <a href="{{ url_for('user.edit_user', user_id=user.id) }}" type="button" class="btn btn-secondary btn-sm">Edit</a>
            <form method="post" action="{{ url_for('user.delete_user', user_id=user.id)}}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete')">
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
        </td>
    </tr>
    {% else %}
    <tr>
        <td colspan="7" class=text-center> No users Found</td>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}